@startuml
!theme blueprint

actor Applications as App

component "OpenTelemetry Collector Forward" as OtelForward

component "OpenTelemetry Collector Opensearch" as OtelOpensearch
database "OpenSearch" as OpenSearch
database "Prometheus" as Prometheus
database "Loki" as Loki
database "Tempo" as Tempo
component "Jaeger" as Jaeger
component "Zipkin" as Zipkin

component "OpenTelemetry Collector Elasticsearch" as OtelElasticsearch
database "Elasticsearch" as Elasticsearch

component "Logstash" as Logstash

App --> OtelForward : Send OTLP (logs, metrics, traces)

OtelForward --> OtelOpensearch : Export OTLP
OtelOpensearch --> OpenSearch : Export logs/metrics/traces
OtelOpensearch --> Prometheus : Export metrics
OtelOpensearch --> Loki : Export logs
OtelOpensearch --> Tempo : Export traces
OtelOpensearch --> Jaeger : Export traces
OtelOpensearch --> Zipkin : Export traces

OtelForward --> OtelElasticsearch : Export OTLP
OtelElasticsearch --> Elasticsearch : Export logs/metrics/traces

OtelForward --> Logstash : Export logs via Syslog RFC5424
Logstash --> Elasticsearch : Send logs
Logstash ..> OpenSearch : (Future) Can send logs
Logstash ..> S3 : (Future)
Logstash ..> Kafka : (Future)

@enduml