version: '3.8'
services:

    #----------------------------------------------------------------------------------------
    jaeger:
        env_file: .env
        image: jaegertracing/all-in-one
        container_name: jaeger
        privileged: true
        tty: true
        ports:
            - ${JAEGER_PORT_GRPC}:14250
            - ${JAEGER_PORT_HTTP}:16686
        networks:
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
