version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    firebird:
        env_file: .env
        container_name: firebird
        privileged: true
        build:
            context: ./
            dockerfile: firebird.dockerfile
            args:
                TZ: ${FIREBIRD_TIMEZONE}
                ISC_PASSWORD: ${FIREBIRD_ISC_PASSWORD}
                FIREBIRD_USER: ${FIREBIRD_USER}
                FIREBIRD_DBNAME: ${FIREBIRD_DBNAME}
        ports:
            - ${FIREBIRD_PORT}:3050
        volumes:
            - ./data/:/etc/firebird/3.0/
        environment:
            TZ: ${FIREBIRD_TIMEZONE}
            FIREBIRD_DATABASE: ${FIREBIRD_DBNAME}
            FIREBIRD_USER: ${FIREBIRD_USER}
            FIREBIRD_PASS: ${FIREBIRD_ISC_PASSWORD}
            ISC_PASSWORD: ${FIREBIRD_ISC_PASSWORD}
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true