version: "3.7"
services:
 
    #----------------------------------------------------------------------------------------
    # Single Environment
    # PHP8
    # APACHE2 (HTTPD)
    php8-apache2:
        env_file: .env
        container_name: php8-apache2
        image: php:8.0-apache
        build:
            context: ./
            dockerfile: php8.dockerfile
        volumes:
#            - type: bind
#              source: ./conf
#              target: /etc/apache2/conf/
#              read_only: false
            - type: bind
              source: ./sites
              target: /var/www/html/
              read_only: false
        ports:
            - ${PHP8_APACHE_PORT}:9000
            - ${PHP8_APACHE_PORT_HTTP}:80
            - ${PHP8_APACHE_PORT_HTTPS}:443
        depends_on:
            - mysql-80
        links:
            - mysql-80
        networks:
            - open_network
    #----------------------------------------------------------------------------------------
    mysql-80:
        env_file: .env
        image: mysql:8.0
        container_name: mysql80
        ports:
            - ${MYSQL80_PORT}:3306
        volumes:
            - "./mysql-80:/var/lib/mysql/"
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        networks:
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
        