version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    zipkin:
        env_file: .env
        container_name: zipkin
        image: openzipkin/zipkin
        ports:
            - ${ZIPKIN_PORT}:9411
        volumes:
            - type: bind
              source: ./shared/
              target: /home/zipkin/shared/
              read_only: false
        environment:
            STORAGE_TYPE: ${ZIPKIN_STORAGE_TYPE}
            SEARCH_ENABLED: ${ZIPKIN_SEARCH_ENABLED}
            #ES_HTTP_LOGGING: ${ZIPKIN_HTTP_LOGGING}
            ES_SSL_NO_VERIFY: ${SECURITY_ZIPKIN_NO_SSL_CHECK}
#        depends_on:
#            - elasticsearch
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
