version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    swagger-generator:
        env_file: .env
        image: swaggerapi/swagger-generator
        container_name: swagger-generator
#        build:
#            context: ./
#            dockerfile: swagger-generator.dockerfile
        ports:
            - ${SWAGGER_GENERATOR_PORT}:8080
        volumes:
            - ./share/:/home/swagger-generator/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
