
## General Settings
cluster.name: ${GENERAL_CLUSTER_NAME}
network.host: ${GENERAL_HOST_ADDRESS}
discovery.type: ${GENERAL_DISCOVERY_TYPE}
xpack.license.self_generated.type: ${GENERAL_LICENSE}

## Security Settings
xpack.security.enabled: ${SECURITY_ENABLE}
xpack.security.authc.token.enabled: ${SECURITY_AUTH_TOKEN_CHECK}
xpack.security.http.ssl.enabled: ${SECURITY_HTTP_SSL}
xpack.security.authc.api_key.enabled: ${SECURITY_API_KEY_CHECK}
