version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    prometheus:
        env_file: .env
        container_name: prometheus
        image: prom/prometheus
        ports:
            - ${PROMETHEUS_PORT}:9090
        volumes:
            - type: bind
              source: ./config/prometheus.yml
              target: /etc/prometheus/prometheus.yml
              read_only: true
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true