version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    sftp-server:
        env_file: .env
        container_name: sftp-server
        build:
            context: ./
            dockerfile: sftp-server.dockerfile
        ports:
            - ${SFTP_HOST_PORT}:${SFTP_PORT}
        volumes:
            - ./uploads/:${SFTP_PATH}
        tty: true
        networks:
            - open_network
        command: ${SFTP_USER}:${SFTP_PASS}:${SFTP_UID}
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
