version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    httpd:
        env_file: .env
        image: httpd:2.4.54
        container_name: httpd
        ports:
            - ${HTTPD_PORT}:80
        privileged: true
        volumes:
            - type: bind
              source: ./htdocs
              target: /usr/local/apache2/htdocs
              read_only: false
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
