version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    postgres:
        env_file: .env
        container_name: postgres
        image: postgres
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            TZ: GMT
        volumes:
            - type: bind
              source: ./PostgresSQL
              target: /var/lib/postgresql/data/
              read_only: false
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true