version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    nginx:
        env_file: .env
        container_name: nginx
        image: nginx:latest
        privileged: true
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - type: bind
              source: ./app/
              target: /var/www/app
              read_only: false
            - type: bind
              source: ./nginx/sample.nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: ./nginx/sample.app.conf
              target: /etc/nginx/conf.d/default.conf
              read_only: true
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
        