version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    webserver-php56:
        env_file: .env
        image: httpd:2.4.54
        container_name: webserver-php56
        ports:
            - ${WEBSERVER_PORT1}:80
            - ${WEBSERVER_PORT2}:443
        privileged: true
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ./webserver/:/home/webserver/
            - ./applications/:/var/www/webserver/
        tty: true
        depends_on:
            - php56
        links:
            - php56
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    php56:
        env_file: .env
        container_name: php56
        build:
            context: ./
            dockerfile: php56.dockerfile
        privileged: true
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        ports:
            - ${PHP_PORT}:9000
        volumes:
            - ./applications/:/var/www/webserver/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
        