version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-21.0.1:
        env_file: .env
        container_name: openjdk-21.0.1
        build:
            context: .
            dockerfile: openjdk-21.0.1.dockerfile
        ports:
            - ${OPENJDK_2101_PORT1}:38801
        volumes:
            - ./microservices/users/:/home/openjdk-21.0.1/microservices/users/
        tty: true
        networks:
            - default
            - open_network
        command: "/usr/bin/java -jar /home/openjdk-21.0.1/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk-21.0.1/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true