version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    sonarqube:
        env_file: .env
        container_name: sonarqube
        image: sonarqube:lts-community
        depends_on:
            - db
        ports:
            - "${SONAR_PORT1}:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db:${SONAR_DB_PORT}/${SONAR_DB}
            - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
            - SONAR_JDBC_PASSWORD=${SONAR_JDBC_USERNAME}
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
    #----------------------------------------------------------------------------------------
    db:
        image: postgres:12
        environment:
            - POSTGRES_USER=${SONAR_DB_USERNAME}
            - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
            - POSTGRES_DB=${SONAR_DB}
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
    #----------------------------------------------------------------------------------------
    sonarqube67:
        env_file: .env
        container_name: sonarqube67
        image: sonarqube:6.7-community
        depends_on:
            - db67
        ports:
            - "${SONAR_PORT2}:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db67:${SONAR_DB_PORT}/${SONAR_DB}
            - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
            - SONAR_JDBC_PASSWORD=${SONAR_JDBC_USERNAME}
        volumes:
            - sonarqube_data67:/opt/sonarqube/data
            - sonarqube_extensions67:/opt/sonarqube/extensions
    #----------------------------------------------------------------------------------------
    db67:
        image: postgres:12
        environment:
            - POSTGRES_USER=${SONAR_DB_USERNAME}
            - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
            - POSTGRES_DB=${SONAR_DB}
        volumes:
            - postgresql67:/var/lib/postgresql
            - postgresql_data67:/var/lib/postgresql/data
    #----------------------------------------------------------------------------------------
    sonarqube97:
        env_file: .env
        container_name: sonarqube97
        image: sonarqube:9.7-community
        depends_on:
            - db97
        ports:
            - "${SONAR_PORT3}:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db97:${SONAR_DB_PORT}/${SONAR_DB}
            - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
            - SONAR_JDBC_PASSWORD=${SONAR_JDBC_USERNAME}
        volumes:
            - sonarqube_data97:/opt/sonarqube/data
            - sonarqube_extensions97:/opt/sonarqube/extensions
    #----------------------------------------------------------------------------------------
    db97:
        image: postgres:12
        environment:
            - POSTGRES_USER=${SONAR_DB_USERNAME}
            - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
            - POSTGRES_DB=${SONAR_DB}
        volumes:
            - postgresql97:/var/lib/postgresql
            - postgresql_data97:/var/lib/postgresql/data
    #----------------------------------------------------------------------------------------
    sonarqube998:
        env_file: .env
        container_name: sonarqube998
        image: sonarqube:9.9.8-community
        depends_on:
            - db998
        ports:
            - "${SONAR_PORT4}:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db998:${SONAR_DB_PORT}/${SONAR_DB}
            - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
            - SONAR_JDBC_PASSWORD=${SONAR_JDBC_USERNAME}
        volumes:
            - sonarqube_data998:/opt/sonarqube/data
            - sonarqube_extensions998:/opt/sonarqube/extensions
    #----------------------------------------------------------------------------------------
    db998:
        image: postgres:12
        environment:
            - POSTGRES_USER=${SONAR_DB_USERNAME}
            - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
            - POSTGRES_DB=${SONAR_DB}
        volumes:
            - postgresql998:/var/lib/postgresql
            - postgresql_data998:/var/lib/postgresql/data
    #----------------------------------------------------------------------------------------
    sonarqube24120:
        env_file: .env
        container_name: sonarqube24120
        image: sonarqube:24.12.0.100206-community
        depends_on:
            - db24120
        ports:
            - "${SONAR_PORT5}:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db24120:${SONAR_DB_PORT}/${SONAR_DB}
            - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
            - SONAR_JDBC_PASSWORD=${SONAR_JDBC_USERNAME}
        volumes:
            - sonarqube_data24120:/opt/sonarqube/data
            - sonarqube_extensions24120:/opt/sonarqube/extensions
    #----------------------------------------------------------------------------------------
    db24120:
        image: postgres:12
        environment:
            - POSTGRES_USER=${SONAR_DB_USERNAME}
            - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
            - POSTGRES_DB=${SONAR_DB}
        volumes:
            - postgresql24120:/var/lib/postgresql
            - postgresql_data24120:/var/lib/postgresql/data
    #----------------------------------------------------------------------------------------

volumes:
    sonarqube_data:
    sonarqube_extensions:
    postgresql:
    postgresql_data:

    sonarqube_data67:
    sonarqube_extensions67:
    postgresql67:
    postgresql_data67:

    sonarqube_data97:
    sonarqube_extensions97:
    postgresql97:
    postgresql_data97:

    sonarqube_data998:
    sonarqube_extensions998:
    postgresql998:
    postgresql_data998:

    sonarqube_data24120:
    sonarqube_extensions24120:
    postgresql24120:
    postgresql_data24120:

networks:
    open_network:
        external: true
