version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    sonarqube:
        env_file: .env
        container_name: sonarqube
        image: sonarqube:lts-community
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://sonar_db:${SONAR_DB_PORT}/${SONAR_DB}
            SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
            SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
            SONAR_JAVA_OPTS: -Xmx512m -Xms512m
        privileged: true
        ports:
            - ${SONAR_PORT}:9000
        volumes:
            - ./share:/home/sonarqube/share
#            - sonarqube_conf:/opt/sonarqube/conf
#            - sonarqube_data:/opt/sonarqube/data
#            - sonarqube_extensions:/opt/sonarqube/extensions
#            - sonarqube_logs:/opt/sonarqube/logs
#            - sonarqube_temp:/opt/sonarqube/temp
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins:/opt/sonarqube/bundled-plugins
        depends_on:
            - sonar_db
        tty: true
        networks:
            - default
            - open_network
        ulimits:
            nofile:
                soft: 131072
                hard: 131072
    #----------------------------------------------------------------------------------------
    sonar_db:
        image: postgres:13
        privileged: true
        environment:
            POSTGRES_USER: ${SONAR_DB_USERNAME}
            POSTGRES_PASSWORD: ${SONAR_DB_PASSWORD}
            POSTGRES_DB: ${SONAR_DB}
        volumes:
            - sonar_db:/var/lib/postgresql
            - sonar_db_data:/var/lib/postgresql/data
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

volumes:
#    sonarqube_conf:
#    sonarqube_data:
#    sonarqube_extensions:
#    sonarqube_logs:
#    sonarqube_temp:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
    sonar_db:
    sonar_db_data:

networks:
    open_network:
        external: true
