version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    sonarqube:
        env_file: .env
        container_name: sonarqube
        image: sonarqube:lts-community
        depends_on:
            - db
        ports:
            - "${SONAR_PORT}:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db:${SONAR_DB_PORT}/${SONAR_DB}
            - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
            - SONAR_JDBC_PASSWORD=${SONAR_JDBC_USERNAME}
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
    #----------------------------------------------------------------------------------------
    db:
        image: postgres:12
        environment:
            - POSTGRES_USER=${SONAR_DB_USERNAME}
            - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}
            - POSTGRES_DB=${SONAR_DB}
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
    #----------------------------------------------------------------------------------------

volumes:
    sonarqube_data:
    sonarqube_extensions:
    postgresql:
    postgresql_data:

networks:
    open_network:
        external: true
