version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    ppk-pem-ppk:
        env_file: .env
        container_name: ppk-pem-ppk
        privileged: true
        #image: amazonlinux
        build:
            context: .
            dockerfile: ppk-pem-ppk.dockerfile
            args:
                PEM_KEY_NAME: ${PEM_KEY_NAME}
                PPK_KEY_NAME: ${PPK_KEY_NAME}
        ports:
            - ${PPK_PEM_PPK_PORT}:35900
        volumes:
            - ./share/pem/:/home/ppk-pem-ppk/pem/
            - ./share/ppk/:/home/ppk-pem-ppk/ppk/
            - ./share/result/:/home/ppk-pem-ppk/result/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
