version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    ec2-service-discovery:
        env_file: .env
        container_name: ec2-service-discovery
        build:
            context: .
            dockerfile: ec2-service-discovery.dockerfile
        ports:
            - ${SERVICE_DISCOVERY_PORT}:8761
        privileged: true
        tty: true
        volumes:
            - ./app/service-discovery/:/home/shared/
        networks:
            - default
            - ec2_java_mysql_rabbitmq_open_network
        command: "/usr/bin/java -jar /home/shared/SERVICE-DISCOVERY-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    ec2-api-gateway:
        env_file: .env
        container_name: ec2-api-gateway
        build:
            context: .
            dockerfile: ec2-api-gateway.dockerfile
        ports:
            - ${API_GATEWAY_PORT}:8765
            - ${API_GATEWAY_HEALTH_PORT}:8081
        privileged: true
        tty: true
        volumes:
            - ./app/api-gateway/:/home/shared/
        networks:
            - default
            - ec2_java_mysql_rabbitmq_open_network
        depends_on:
            - ec2-service-discovery
        links:
            - ec2-service-discovery
        command: "/usr/bin/java -jar /home/shared/API-GATEWAY-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    ec2-rabbitmq-reader:
        env_file: .env
        container_name: ec2-rabbitmq-reader
        build:
            context: .
            dockerfile: ec2-rabbitmq-reader.dockerfile
        privileged: true
        tty: true
        volumes:
            - ./app/rabbitmq-reader/:/home/shared/
        networks:
            - default
            - ec2_java_mysql_rabbitmq_open_network
        depends_on:
            - ec2-service-discovery
            - ec2-api-gateway
        links:
            - ec2-service-discovery
            - ec2-api-gateway
        command: "/usr/bin/java -jar /home/shared/RABBITMQ-READER-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    ec2-application-demo:
        env_file: .env
        container_name: ec2-application-demo
        build:
            context: .
            dockerfile: ec2-application-demo.dockerfile
        privileged: true
        tty: true
        volumes:
            - ./app/application-demo/:/home/shared/
        networks:
            - default
            - ec2_java_mysql_rabbitmq_open_network
        depends_on:
            - ec2-service-discovery
            - ec2-api-gateway
        links:
            - ec2-service-discovery
            - ec2-api-gateway
        command: "/usr/bin/java -jar /home/shared/APPLICATION-DEMO-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
#    rabbitmq-3.6.10--image:
#        env_file: .env
#        image: rabbitmq:3.6.10
#        container_name: rabbitmq-3.6.10--image
#        ports:
#            - ${RABBITMQ_PORT_3610_IMAGE}:5672
#            - ${RABBITMQ_HTTP_PORT_3610_IMAGE}:15672
#        volumes:
#            - ./rabbitmq/3.6.10--image/lib:/var/lib/rabbitmq/
#            - ./rabbitmq/3.6.10--image/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
#        environment:
#            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
#            RABBITMQ_PLUGINS_DIR: ${RABBITMQ_PLUGINS_DIR}
#        tty: true
#        networks:
#            - ec2_java_mysql_rabbitmq_open_network
    #----------------------------------------------------------------------------------------
#    rabbitmq-3.9.8--image:
#        env_file: .env
#        image: rabbitmq:3.9.8
#        container_name: rabbitmq-3.9.8--image
#        ports:
#            - ${RABBITMQ_PORT_398_IMAGE}:5672
#            - ${RABBITMQ_HTTP_PORT_398_IMAGE}:15672
#        volumes:
#            - ./rabbitmq/3.9.8--image/logs:/var/log/rabbitmq/log
#            - ./rabbitmq/3.9.8--image/lib:/var/lib/rabbitmq
#            - ./rabbitmq/3.9.8--image/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#            - ./rabbitmq/3.9.8--image/config/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
#            - ./rabbitmq/3.9.8--image/config/10-defaults.conf:/etc/rabbitmq/conf.d/10-defaults.conf
#            - ./rabbitmq/3.9.8--image/config/20-management_agent.disable_metrics_collector.conf:/etc/rabbitmq/conf.d/20-management_agent.disable_metrics_collector.conf
#        environment:
#            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
#            RABBITMQ_PLUGINS_DIR: ${RABBITMQ_PLUGINS_DIR}
#        tty: true
#        networks:
#            - ec2_java_mysql_rabbitmq_open_network
    #----------------------------------------------------------------------------------------
#    rabbitmq-3.6.10--dockerfile:
#        env_file: .env
#        build:
#            context: .
#            dockerfile: ec2-rabbit-3.6.10.dockerfile
#        container_name: rabbitmq-3.6.10--dockerfile
#        ports:
#            - ${RABBITMQ_PORT_3610_DOCKERFILE}:5672
#            - ${RABBITMQ_HTTP_PORT_3610_DOCKERFILE}:15672
#        volumes:
#            - type: bind
#              source: ./rabbitmq/3.6.10--dockerfile/lib/
#              target: /var/lib/rabbitmq/
#              read_only: false
#            - type: bind
#              source: ./rabbitmq/3.6.10--dockerfile/config/rabbitmq.conf
#              target: /etc/rabbitmq/rabbitmq.conf
#              read_only: false
#        environment:
#            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
#            RABBITMQ_PLUGINS_DIR: ${RABBITMQ_PLUGINS_DIR}
#        tty: true
#        networks:
#            - ec2_java_mysql_rabbitmq_open_network
    #----------------------------------------------------------------------------------------
    mysql8:
        env_file: .env
        image: mysql:8.0
        container_name: mysql8
        ports:
            - ${MYSQL80_PORT}:3306
        volumes:
            - type: bind
              source: ./mysql8
              target: /var/lib/mysql/
              read_only: false
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        tty: true
        networks:
            - ec2_java_mysql_rabbitmq_open_network
    #----------------------------------------------------------------------------------------

networks:
    ec2_java_mysql_rabbitmq_open_network:
        external: true
