version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    ec2_service_discovery:
        env_file: .env
        container_name: ec2_service_discovery
        build:
            context: .
            dockerfile: ec2_service_discovery.dockerfile
        ports:
            - ${SERVICE_DISCOVERY_PORT}:8761
        privileged: true
        tty: true
        volumes:
            - ./app/service_discovery/:/home/shared/
        networks:
            - default
            - open_network
        depends_on:
            - mysql8
            - rabbitmq
        links:
            - mysql8
            - rabbitmq
        #command: "/usr/bin/java -jar /home/shared/SERVICE-DISCOVERY-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    ec2_api_gateway:
        env_file: .env
        container_name: ec2_api_gateway
        build:
            context: .
            dockerfile: ec2_api_gateway.dockerfile
        ports:
            - ${API_GATEWAY_PORT}:8765
            - ${API_GATEWAY_HEALTH_PORT}:8081
        privileged: true
        tty: true
        volumes:
            - ./app/api_gateway/:/home/shared/
        networks:
            - default
            - open_network
        depends_on:
            - mysql8
            - rabbitmq
            - ec2_service_discovery
        links:
            - mysql8
            - rabbitmq
            - ec2_service_discovery
        #command: "/usr/bin/java -jar /home/shared/API-GATEWAY-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    ec2_rabbitmq_reader:
        env_file: .env
        container_name: ec2_rabbitmq_reader
        build:
            context: .
            dockerfile: ec2_rabbitmq_reader.dockerfile
        privileged: true
        tty: true
        volumes:
            - ./app/rabbitmq_reader/:/home/shared/
        networks:
            - default
            - open_network
        depends_on:
            - mysql8
            - rabbitmq
            - ec2_service_discovery
            - ec2_api_gateway
        links:
            - mysql8
            - rabbitmq
            - ec2_service_discovery
            - ec2_api_gateway
        #command: "/usr/bin/java -jar /home/shared/RABBITMQ-READER-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    ec2_application_demo:
        env_file: .env
        container_name: ec2_application_demo
        build:
            context: .
            dockerfile: ec2_application_demo.dockerfile
        privileged: true
        tty: true
        volumes:
            - ./app/application_demo/:/home/shared/
        networks:
            - default
            - open_network
        depends_on:
            - mysql8
            - rabbitmq
            - ec2_service_discovery
            - ec2_api_gateway
        links:
            - mysql8
            - rabbitmq
            - ec2_service_discovery
            - ec2_api_gateway
        #command: "/usr/bin/java -jar /home/shared/APPLICATION-DEMO-22.01.1-SNAPSHOT.jar --spring.config.location=/home/shared/application.properties"
    #----------------------------------------------------------------------------------------
    rabbitmq:
        env_file: .env
        image: rabbitmq:3.9.8
        container_name: rabbitmq
        ports:
            - ${RABBITMQ_PORT}:5672
            - ${RABBITMQ_HTTP_PORT}:15672
        volumes:
            - type: bind
              source: ./rabbitmq
              target: /var/lib/rabbitmq/
              read_only: false
            - type: bind
              source: ./rabbitmq/rabbitmq.conf
              target: /etc/rabbitmq/conf.d/rabbitmq.conf
              read_only: false
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        tty: true
        networks:
            - open_network
    #----------------------------------------------------------------------------------------
    mysql8:
        env_file: .env
        image: mysql:8.0
        container_name: mysql8
        ports:
            - ${MYSQL80_PORT}:3306
        volumes:
            - type: bind
              source: ./mysql8
              target: /var/lib/mysql/
              read_only: false
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        tty: true
        networks:
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
