version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    mailhog-ubuntu2004:
        env_file: .env
        container_name: mailhog-ubuntu2004
        build:
            context: ./
            dockerfile: mailhog.dockerfile
        ports:
            - ${MAILHOG_UBUNTU_HTTP_PORT}:8025
            - ${MAILHOG_UBUNTU_SMTP_PORT}:1025
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    mailhog:
        env_file: .env
        container_name: mailhog
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - ${MAILHOG_HTTP_PORT}:8025
            - ${MAILHOG_SMTP_PORT}:1025
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
