version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    nginx:
        env_file: .env
        container_name: nginx
        image: nginx:latest
        privileged: true
        ports:
            - ${NGINX_PORT1}:80
            - ${NGINX_PORT2}:81
            - ${NGINX_PORT3}:82
            - ${NGINX_PORT4}:83
            - ${NGINX_PORT5}:84
            - ${NGINX_REVERSE_PROXY_PORT}:8585
            - ${NGINX_LOAD_BALANCE_PORT}:8686
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ./logs:/etc/nginx/logs
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/proxy.conf:/etc/nginx/proxy.conf
            - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./nginx/mime.types:/etc/nginx/mime.types
            - ./nginx/htdocs/403.html:/usr/share/nginx/html/403.html
            - ./nginx/htdocs/404.html:/usr/share/nginx/html/404.html
            - ./nginx/htdocs/500.html:/usr/share/nginx/html/500.html
            - ./nginx/htdocs/index.html:/usr/share/nginx/html/index.html
            - ./nginx/htdocs/nginx.png:/usr/share/nginx/html/nginx.png
            - ./applications/:/var/www/webserver/applications/
        working_dir: /etc/nginx
        links:
            - php-7.4.0
            - php-8.0.0
            - php-8.1.0
            - php-8.2.2
            - php-8.2.13
        depends_on:
            - php-7.4.0
            - php-8.0.0
            - php-8.1.0
            - php-8.2.2
            - php-8.2.13
        tty: true
        networks:
            - default
            - nginx_reverse_proxy_php8_open_network
    #----------------------------------------------------------------------------------------
    php-7.4.0:
        env_file: .env
        container_name: php-7.4.0
        build:
            context: ./php/7.4.0
            dockerfile: php-7.4.0.dockerfile
        ports:
            - ${PHP740_PORT}:9000
        volumes:
            - ./php/7.4.0/conf/:/home/php/conf/
            - ./php/7.4.0/shared/:/home/php/shared/
            - ./applications/php-7.4.0/:/var/www/webserver/applications/php-7.4.0/
        networks:
            - nginx_reverse_proxy_php8_open_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.0.0:
        env_file: .env
        container_name: php-8.0.0
        build:
            context: ./php/8.0.0
            dockerfile: php-8.0.0.dockerfile
        ports:
            - ${PHP800_PORT}:9000
        volumes:
            - ./php/8.0.0/conf/:/home/php/conf/
            - ./php/8.0.0/shared/:/home/php/shared/
            - ./applications/php-8.0.0/:/var/www/webserver/applications/php-8.0.0/
        networks:
            - nginx_reverse_proxy_php8_open_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.1.0:
        env_file: .env
        container_name: php-8.1.0
        build:
            context: ./php/8.1.0
            dockerfile: php-8.1.0.dockerfile
        ports:
            - ${PHP810_PORT}:9000
        volumes:
            - ./php/8.1.0/conf/:/home/php/conf/
            - ./php/8.1.0/shared/:/home/php/shared/
            - ./applications/php-8.1.0/:/var/www/webserver/applications/php-8.1.0/
        networks:
            - nginx_reverse_proxy_php8_open_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.2.2:
        env_file: .env
        container_name: php-8.2.2
        build:
            context: ./php/8.2.2
            dockerfile: php-8.2.2.dockerfile
        ports:
            - ${PHP822_PORT}:9000
        volumes:
            - ./php/8.2.2/conf/:/home/php/conf/
            - ./php/8.2.2/shared/:/home/php/shared/
            - ./applications/php-8.2.2/:/var/www/webserver/applications/php-8.2.2/
        networks:
            - nginx_reverse_proxy_php8_open_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.2.13:
        env_file: .env
        container_name: php-8.2.13
        build:
            context: ./php/8.2.13
            dockerfile: php-8.2.13.dockerfile
        ports:
            - ${PHP8213_PORT}:9000
        volumes:
            - ./php/8.2.13/conf/:/home/php/conf/
            - ./php/8.2.13/shared/:/home/php/shared/
            - ./applications/php-8.2.13/:/var/www/webserver/applications/php-8.2.13/
        networks:
            - nginx_reverse_proxy_php8_open_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    
networks:
    nginx_reverse_proxy_php8_open_network:
        external: true
        