version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-11:
        env_file: .env
        container_name: openjdk-11
        build:
            context: .
            dockerfile: openjdk-11.dockerfile
        volumes:
            - ./microservices/users/:/home/openjdk11/microservices/users/
        ports:
            - ${OPENJDK_11_PORT1}:38801
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk11/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk11/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true