version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    artifactory-7.77.3-redhat:
        env_file: .env
        container_name: artifactory-7.77.3-redhat
        build:
            context: .
            dockerfile: artifactory-7.77.3-redhat.dockerfile
        ports:
            - ${ARTIFACTORY_7773_REDHAT_PORT1}:80
            - ${ARTIFACTORY_7773_REDHAT_PORT2}:8080
            - ${ARTIFACTORY_7773_REDHAT_PORT3}:8081
            - ${ARTIFACTORY_7773_REDHAT_PORT4}:8082
            - ${ARTIFACTORY_7773_REDHAT_PORT5}:8181
        volumes:
            - ./shared/:/home/artifactory-7.77.3/
        tty: true
        command: "/bin/bash /home/artifactory/artifactory-oss-7.77.3/app/bin/artifactory.sh"
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
