version: '3.7'
services:
  elasticsearch:
    env_file: .env
    container_name: elasticsearch
    image: elasticsearch:${STACK_VERSION}
    ports:
      - '9200:9200'
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: elasticsearch
        target: /usr/share/elasticsearch/data
        read_only: false
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    env_file: .env
    container_name: kibana
    image: kibana:${STACK_VERSION}
    ports:
      - '5601:5601'
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true

  logstash:
    env_file: .env
    container_name: logstash
    image: logstash:${STACK_VERSION}
    ports:
      - '5000:5000'
      - '8080:8080'
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true

volumes:
  elastcsearch:
