version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    logstash:
        env_file: .env
        container_name: logstash
        image: logstash:${GENERAL_STACK_VERSION}
        ports:
            - ${LOGSTASH_PORT_HTTP}:8080
            - ${LOGSTASH_PORT_1}:5044
            - ${LOGSTASH_PORT_2}:9600
            - ${LOGSTASH_TCP_PORT}:5000/tcp
            - ${LOGSTASH_UDP_PORT}:5000/udp
        volumes:
            - type: bind
              source: ./pipeline
              target: /usr/share/logstash/pipeline
              read_only: true
            - type: bind
              source: ./config/logstash.yml
              target: /usr/share/logstash/config/logstash.yml
              read_only: true
        environment:
            ELASTIC_VERSION: ${GENERAL_STACK_VERSION}
            LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
            LS_JAVA_OPTS: ${LOGSTASH_JAVA_OPTS}
        depends_on:
            - elasticsearch
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
