version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-11.0.21:
        env_file: .env
        container_name: openjdk-11.0.21
        build:
            context: .
            dockerfile: openjdk-11.0.21.dockerfile
        ports:
            - ${OPENJDK_11021_PORT1}:38801
        volumes:
            - ./microservices/users/:/home/openjdk-11.0.21/microservices/users/
        tty: true
        networks:
            - default
            - open_network
        command: "/usr/bin/java -jar /home/openjdk-11.0.21/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk-11.0.21/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true