version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    nginx:
        env_file: .env
        container_name: nginx
        image: nginx:latest
        privileged: true
        ports:
            - ${NGINX_PORT1}:85
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/proxy.conf:/etc/nginx/proxy.conf
            - ./etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./etc/nginx/mime.types:/etc/nginx/mime.types
            - ./etc/nginx/conf:/etc/nginx/conf
            - ./etc/nginx/logs:/etc/nginx/logs
            - ./htdocs:/var/www/htdocs
        working_dir: /etc/nginx
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    
networks:
    open_network:
        external: true
        