version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    nginx:
        env_file: .env
        container_name: nginx
        image: nginx:latest
        privileged: true
        ports:
            - ${NGINX_PORT}:85
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ./nginx/logs:/etc/nginx/logs
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/proxy.conf:/etc/nginx/proxy.conf
            - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./nginx/mime.types:/etc/nginx/mime.types
            - ./nginx/htdocs/403.html:/usr/share/nginx/html/403.html
            - ./nginx/htdocs/404.html:/usr/share/nginx/html/404.html
            - ./nginx/htdocs/500.html:/usr/share/nginx/html/500.html
            - ./nginx/htdocs/index.html:/usr/share/nginx/html/index.html
            - ./nginx/htdocs/nginx.png:/usr/share/nginx/html/nginx.png
            - ./applications/:/var/www/webserver/applications/
        working_dir: /etc/nginx
        tty: true
        networks:
            - default
            - nginx_reverse_proxy_open_network
    #----------------------------------------------------------------------------------------
    
networks:
    nginx_reverse_proxy_open_network:
        external: true
        