version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    traefik:
        image: traefik:v2.2
        container_name: traefik
        restart: always
        privileged: true
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
            - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
            - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.myresolver.acme.email=huntercodexs@gmail.com"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - ${TRAEFIK_HTTP_PORT}:80
            - ${TRAEFIK_HTTPS_PORT}:443
        networks:
            - open_network
        volumes:
            - ./var/run/docker.sock:/var/run/docker.sock
            - ./letsencrypt:/letsencrypt
        tty: true
    #----------------------------------------------------------------------------------------
    nexus:
        container_name: nexus
        image: sonatype/nexus3
        restart: always
        privileged: true
        networks:
            - open_network
        volumes:
            - ./nexus-data:/nexus-data
        labels:
            - traefik.port=8081
            - traefik.http.routers.nexus.rule=Host(`NEXUS.localhost`)
            - traefik.enable=true
            - traefik.http.routers.nexus.entrypoints=websecure
            - traefik.http.routers.nexus.tls=true
            - traefik.http.routers.nexus.tls.certresolver=myresolver
        tty: true
    #----------------------------------------------------------------------------------------
    
networks:
    open_network:
        external: true
