version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-21:
        env_file: .env
        container_name: openjdk-21
        build:
            context: .
            dockerfile: openjdk-21.dockerfile
        volumes:
            - ./microservices/users/:/home/openjdk21/microservices/users/
        ports:
            - ${OPENJDK_21_PORT1}:38801
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk21/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk21/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true