version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    centos:
        env_file: .env
        container_name: centos
        #image: centos
        build:
            context: .
            dockerfile: centos.dockerfile
        ports:
            - ${CENTOS_PORT}:35900
        privileged: true
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
