version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    jenkins-latest:
        env_file: .env
        container_name: jenkins-latest
        build:
            context: ./
            dockerfile: jenkins-latest.dockerfile
        privileged: true
        user: root
        ports:
            - ${JENKINS_HTTP_PORT}:8080
            - ${JENKINS_AGENT_PORT}:50000
        volumes:
            - ./share/configuration:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    
networks:
    open_network:
        external: true
