version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    apache2_php8:
        env_file: .env
        container_name: apache2_php8
        build:
            context: ./
            dockerfile: apache2_php8.dockerfile
        privileged: true
        volumes:
            # Application files
            - type: bind
              source: ./app/
              target: /var/www/html
              read_only: false
            # App settings
            - type: bind
              source: ./apache2/conf/app.conf
              target: /etc/apache2/sites-available/app.conf
              read_only: false
            # Default settings
            - type: bind
              source: ./apache2/conf/000-default.conf
              target: /etc/apache2/sites-available/000-default.conf
              read_only: false
        ports:
            - ${APACHE2_PHP8_PORT1}:80
            - ${APACHE2_PHP8_PORT2}:8080
            - ${APACHE2_PHP8_PORT3}:38989
        networks:
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true