version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    webserver-php71:
        env_file: .env
        image: httpd:2.4.54
        container_name: webserver-php71
        ports:
            - ${WEBSERVER_PORT1}:80
            - ${WEBSERVER_PORT2}:443
        privileged: true
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ./webserver/:/home/webserver/
            - ./webserver/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./webserver/conf/webserver.conf:/usr/local/apache2/conf/webserver.conf
            - ./webserver/conf/htdocs/index.html:/usr/local/apache2/htdocs/index.html
            - ./applications/:/var/www/webserver/
        tty: true
        depends_on:
            - php71
        links:
            - php71
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    php71:
        env_file: .env
        container_name: php71
        build:
            context: ./
            dockerfile: php71.dockerfile
        privileged: true
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        ports:
            - ${PHP_PORT}:9000
        volumes:
            - ./applications/:/var/www/webserver/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
        