receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

exporters:
    otlp/elasticsearch:
        endpoint: opentelemetry-collector-elasticsearch:4317
        tls:
            insecure: true
    otlp/opensearch:
        endpoint: opentelemetry-collector-opensearch:4317
        tls:
            insecure: true
    syslog/logstash:
        endpoint: logstash:5000
        protocol: rfc5424

service:
    pipelines:
        logs:
            receivers: [otlp]
            exporters: [otlp/elasticsearch, otlp/opensearch, syslog/logstash]
        traces:
            receivers: [otlp]
            exporters: [otlp/elasticsearch, otlp/opensearch]
        metrics:
            receivers: [otlp]
            exporters: [otlp/elasticsearch, otlp/opensearch]