receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

exporters:
    debug:
    prometheus:
        endpoint: "0.0.0.0:8889"
    otlp/elasticsearch:
        endpoint: opentelemetry-collector-elasticsearch:4317
        tls:
            insecure: true
    otlp/opensearch:
        endpoint: opentelemetry-collector-opensearch:4317
        tls:
            insecure: true
    syslog/logstash:
        endpoint: tcp://logstash:5000
        protocol: rfc5424

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/elasticsearch, otlp/opensearch]
        metrics:
            receivers: [otlp]
            exporters: [debug, prometheus, otlp/elasticsearch, otlp/opensearch]
        logs:
            receivers: [otlp]
            exporters: [otlp/elasticsearch, otlp/opensearch, syslog/logstash]
    telemetry:
        metrics:
            address: "0.0.0.0:8888"
            level: "detailed"
        logs:
            level: "debug"