receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
        send_batch_size: 100
        timeout: 10s
    transform/syslog:
        log_statements:
            - context: log
              statements:
                  - set(attributes["message"], body)
    transform/http:
        log_statements:
            - context: log
              statements:
                - set(attributes["message"], body)

exporters:
    debug:
    prometheus:
        endpoint: "0.0.0.0:8889"
    otlp/elasticsearch:
        endpoint: opentelemetry-collector-elasticsearch:4317
        tls:
            insecure: true #true|false
            #ca_file:
            #cert_file:
            #key_file:
    otlp/opensearch:
        endpoint: opentelemetry-collector-opensearch:4317
        tls:
            insecure: true #true|false
            #ca_file:
            #cert_file:
            #key_file:
    syslog/logstash:
        network: udp
        protocol: rfc5424
        endpoint: logstash
        port: 5000
    otlphttp/logstash:
        endpoint: "http://logstash:8080"
        tls:
            insecure: true #true|false
            #ca_file:
            #cert_file:
            #key_file:

service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/elasticsearch, otlp/opensearch]

        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, prometheus, otlp/elasticsearch, otlp/opensearch]

        logs/standard:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/elasticsearch, otlp/opensearch]

        logs/syslog:
            receivers: [otlp]
            processors: [batch, transform/syslog]
            exporters: [syslog/logstash]

        logs/http:
            receivers: [otlp]
            processors: [batch, transform/http]
            exporters: [debug, otlphttp/logstash]

    telemetry:
        metrics:
            address: "0.0.0.0:8888"
            level: "detailed"
        logs:
            level: "debug"