version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    ubuntu-20.04:
        env_file: .env
        #image: ubuntu:20.04
        container_name: ubuntu-20.04
        build:
            context: ./
            dockerfile: ubuntu-20.04.dockerfile
        ports:
            - ${UBUNTU2004_PORT}:35900
        volumes:
            - ./share/:/home/ubuntu/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
