version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    webserver:
        env_file: .env
        image: httpd:2.4.54
        container_name: webserver
        ports:
            - ${WEBSERVER740_PORT1}:80
            - ${WEBSERVER800_PORT1}:81
            - ${WEBSERVER810_PORT1}:82
            - ${WEBSERVER822_PORT1}:83
            - ${WEBSERVER8213_PORT1}:84
        privileged: true
        volumes:
            - ./applications/:/var/www/webserver/
            - ./webserver/conf/:/home/webserver/conf/
            - ./webserver/shared/:/home/webserver/shared/
        tty: true
        depends_on:
            - php-7.4.0
            - php-8.0.0
            - php-8.1.0
            - php-8.2.2
            - php-8.2.13
        links:
            - php-7.4.0
            - php-8.0.0
            - php-8.1.0
            - php-8.2.2
            - php-8.2.13
        networks:
            - httpd_php8_separated_network
        #command: "/home/webserver/conf/webserver.sh"
    #----------------------------------------------------------------------------------------
    php-7.4.0:
        env_file: .env
        container_name: php-7.4.0
        build:
            context: ./php/7.4.0
            dockerfile: php-7.4.0.dockerfile
        ports:
            - ${PHP740_PORT}:9000
        volumes:
            - ./php/7.4.0/conf/:/home/php/conf/
            - ./php/7.4.0/shared/:/home/php/shared/
            - ./applications/php-7.4.0/:/var/www/webserver/php-7.4.0
        networks:
            - httpd_php8_separated_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.0.0:
        env_file: .env
        container_name: php-8.0.0
        build:
            context: ./php/8.0.0
            dockerfile: php-8.0.0.dockerfile
        ports:
            - ${PHP800_PORT}:9000
        volumes:
            - ./php/8.0.0/conf/:/home/php/conf/
            - ./php/8.0.0/shared/:/home/php/shared/
            - ./applications/php-8.0.0/:/var/www/webserver/php-8.0.0
        networks:
            - httpd_php8_separated_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.1.0:
        env_file: .env
        container_name: php-8.1.0
        build:
            context: ./php/8.1.0
            dockerfile: php-8.1.0.dockerfile
        ports:
            - ${PHP810_PORT}:9000
        volumes:
            - ./php/8.1.0/conf/:/home/php/conf/
            - ./php/8.1.0/shared/:/home/php/shared/
            - ./applications/php-8.1.0/:/var/www/webserver/php-8.1.0
        networks:
            - httpd_php8_separated_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.2.2:
        env_file: .env
        container_name: php-8.2.2
        build:
            context: ./php/8.2.2
            dockerfile: php-8.2.2.dockerfile
        ports:
            - ${PHP822_PORT}:9000
        volumes:
            - ./php/8.2.2/conf/:/home/php/conf/
            - ./php/8.2.2/shared/:/home/php/shared/
            - ./applications/php-8.2.2/:/var/www/webserver/php-8.2.2
        networks:
            - httpd_php8_separated_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.2.13:
        env_file: .env
        container_name: php-8.2.13
        build:
            context: ./php/8.2.13
            dockerfile: php-8.2.13.dockerfile
        ports:
            - ${PHP8213_PORT}:9000
        volumes:
            - ./php/8.2.13/conf/:/home/php/conf/
            - ./php/8.2.13/shared/:/home/php/shared/
            - ./applications/php-8.2.13/:/var/www/webserver/php-8.2.13
        networks:
            - httpd_php8_separated_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------

networks:
    httpd_php8_separated_network:
        external: true
