version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    redis:
        env_file: .env
        container_name: redis
        build:
            context: ./
            dockerfile: redis.dockerfile
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - type: bind
              source: ./data
              target: /data/
              read_only: false
        command: redis-server --requirepass ${REDIS_AUTH}
        tty: true
        networks:
            - default
            - open_network
    #-----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
