#---
#
### General Settings
#server.name: ${KIBANA_SERVER_NAME}
#server.host: ${HOST_ADDRESS}
#server.port: ${KB_PORT}
#elasticsearch.hosts: ${ELASTICSEARCH_HOST}
#monitoring.ui.container.elasticsearch.enabled: ${MONITORING_ES}
#
### X-Pack security credentials
#elasticsearch.username: ${KIBANA_USERNAME}
#elasticsearch.password: ${KIBANA_PASSWORD}
#xpack.security.encryptionKey: ${KIBANA_ENC_KEY}
#xpack.reporting.kibanaServer.hostname: ${KIBANA_HOST_NAME}
#xpack.reporting.roles.enabled: ${KIBANA_REPORT_ROLES}
