version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        ports:
            - ${OPENJDK_8U212_PORT}:38001
        volumes:
            - ./app/:/home/openjdk8u212/
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk8u212/JAVA-MYSQL-22.01.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u212/application.properties"
    #----------------------------------------------------------------------------------------
    mysql-80:
        env_file: .env
        image: mysql:8.0
        container_name: mysql-80
        ports:
            - ${MYSQL80_PORT}:3306
        volumes:
            - ./lib:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true