version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    redhat-rpm:
        env_file: .env
        container_name: redhat-rpm
        #image: redhat
        build:
            context: .
            dockerfile: redhat-rpm.dockerfile
        ports:
            - ${REDHAT_RPM_PORT}:35900
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
