version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    tomcat:
        env_file: .env
        container_name: tomcat
        #Using image
#        image: tomcat:9.0
        #Using builder
        build:
            context: ./
            dockerfile: tomcat.dockerfile
        ports:
            - ${TOMCAT_PORT1}:8080
            - ${TOMCAT_PORT2}:8888
            - ${TOMCAT_PORT3}:8989
        privileged: true
        environment:
            CATALINA_BASE: /usr/local/tomcat
            CATALINA_HOME: /usr/local/tomcat
            CATALINA_TMPDIR: /usr/local/tomcat/temp
            JRE_HOME: /opt/java/openjdk
            JAVA_HOME: /usr/bin/java
            CLASSPATH: /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
        volumes:
            - type: bind
              source: ./share
              target: /home/tomcat
              read_only: false
            - type: bind
              source: ./conf
              target: /usr/local/tomcat/conf/
              read_only: false
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
