version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    rabbitmq-3-6-10:
        env_file: .env
        container_name: rabbitmq-3-6-10
        build:
            context: .
            dockerfile: amazonlinux-rabbit-3-6-10.dockerfile
        ports:
            - ${RABBITMQ_PORT}:5672
            - ${RABBITMQ_HTTP_PORT}:15672
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
