scrape_configs:
  ############################################# Microservice identification sample - 1
  - job_name: 'microservice-product'
    scrape_interval: 2s
    metrics_path: "${PROMETHEUS_ENDPOINT}"
    static_configs:
      - targets: ['localhost:9001']
  ############################################# Microservice identification sample - 2
  - job_name: 'microservice-order'
    scrape_interval: 2s
    metrics_path: "${PROMETHEUS_ENDPOINT}"
    static_configs:
      - targets: ['localhost:9002']
  ############################################# Microservice identification sample - 3
  - job_name: 'microservice-client'
    scrape_interval: 2s
    metrics_path: "${PROMETHEUS_ENDPOINT}"
    static_configs:
      - targets: ['localhost:8080']