version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    artifactory-6.23.23:
        env_file: .env
        container_name: artifactory-6.23.23
        build:
            context: .
            dockerfile: artifactory-6.23.23.dockerfile
        ports:
            - ${ARTIFACTORY_62323_PORT1}:80
            - ${ARTIFACTORY_62323_PORT2}:8080
            - ${ARTIFACTORY_62323_PORT3}:8081
            - ${ARTIFACTORY_62323_PORT4}:8082
            - ${ARTIFACTORY_62323_PORT5}:8181
        volumes:
            - ./shared/:/home/artifactory-6.23.23/
        tty: true
        command: "/bin/bash /home/artifactory/artifactory-oss-6.23.23/bin/artifactory.sh"
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
