version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    rabbitmq-3.12.12:
        env_file: .env
        container_name: rabbitmq-3.12.12
        #image: rabbitmq:3.12.12
        build:
            context: ./
            dockerfile: amazonlinux-rabbit-3.12.12.dockerfile
        ports:
            - ${RABBITMQ_PORT}:5672
            - ${RABBITMQ_HTTP_PORT}:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true