version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u222:
        env_file: .env
        container_name: openjdk-8u222
        build:
            context: .
            dockerfile: openjdk-8u222.dockerfile
        ports:
            - ${OPENJDK_8U222_PORT1}:38801
        volumes:
            - ./microservices/users/:/home/openjdk8u222/microservices/users/
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk8u222/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u222/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true