receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
    attributes:
        actions:
            - key: team
              value: huntercodexs
              action: insert

exporters:
    debug:

    ### 1. OTEL-FORWARD > OTEL-ELASTICSEARCH > KIBANA
    elasticsearch:
        endpoints: [ "http://elasticsearch:9200" ]
        user: "${ELASTIC_USERNAME}"
        password: "${ELASTIC_PASSWORD}"
        logs_index: "otel-collector-elasticsearch-v1-2025.06.08"
        tls:
            insecure: true

    ### 2. OTEL-FORWARD > OTEL-ELASTICSEARCH > ZIPKIN
    zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
        tls:
            insecure: true

    ### 3. OTEL-FORWARD > OTEL-ELASTICSEARCH > PROMETHEUS
    prometheus:
        endpoint: "0.0.0.0:8889"

service:
    extensions: [zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, elasticsearch, zipkin]
        metrics:
            receivers: [otlp]
            processors: [batch, attributes]
            exporters: [debug, prometheus, elasticsearch]
        logs:
            receivers: [otlp]
            processors: [batch, attributes]
            exporters: [debug, elasticsearch]
    telemetry:
        metrics:
            address: "0.0.0.0:8888"
            level: "detailed"
        logs:
            level: "debug"

extensions:
    zpages:
        endpoint: "0.0.0.0:55679"
