receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
    attributes:
        actions:
            - key: team
              action: insert
              value: huntercodexs

exporters:
    debug:
    elasticsearch:
        endpoints: [ "http://elasticsearch:9200" ]
        #index: "otel-logs"
        user: "${ELASTIC_USERNAME}"
        password: "${ELASTIC_PASSWORD}"
        tls:
            insecure: true

service:
    extensions: [zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, elasticsearch]
        metrics:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, elasticsearch]
        logs:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, elasticsearch]

extensions:
    zpages:
        endpoint: "0.0.0.0:55679"