receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
    attributes:
        actions:
            - key: team
              value: huntercodexs
              action: insert

exporters:
    debug:
    prometheus:
        endpoint: "0.0.0.0:8889"
    elasticsearch:
        endpoints: [ "http://elasticsearch:9200" ]
        #index: "otel-logs"
        user: "${ELASTIC_USERNAME}"
        password: "${ELASTIC_PASSWORD}"
        tls:
            insecure: true
    zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
        tls:
            insecure: true

service:
    extensions: [zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, elasticsearch, zipkin]
        metrics:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, prometheus, elasticsearch]
        logs:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, elasticsearch]
    telemetry:
        metrics:
            address: "0.0.0.0:8888"
            level: "detailed"
        logs:
            level: "debug"

extensions:
    zpages:
        endpoint: "0.0.0.0:55679"