version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    amazonlinux:
        env_file: .env
        container_name: amazonlinux
        #image: amazonlinux
        build:
            context: .
            dockerfile: amazonlinux.dockerfile
        ports:
            - ${AMAZONLINUX_PORT}:35900
        privileged: true
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
