version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u221:
        env_file: .env
        container_name: openjdk-8u221
        build:
            context: .
            dockerfile: openjdk-8u221.dockerfile
        ports:
            - ${OPENJDK_8U221_PORT1}:38801
        volumes:
            - ./microservices/users/:/home/openjdk8u221/microservices/users/
        tty: true
        networks:
            - default
            - open_network
        command: "/usr/bin/java -jar /home/openjdk8u221/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u221/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true