receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
    attributes:
        actions:
            - key: team
              action: insert
              value: huntercodexs

exporters:
    debug:
    prometheus:
        endpoint: "0.0.0.0:8889"
    loki:
        endpoint: http://loki:3100/loki/api/v1/push
    otlp:
        endpoint: tempo:4317
        tls:
            insecure: true
    otlphttp:
        endpoint: http://jaeger:4318
        tls:
            insecure: true
    zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
        tls:
            insecure: true
    elasticsearch: # Opensearch
        endpoints: [ "https://opensearch-node:9200" ]
        user: "admin"
        password: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
        tls:
            insecure: true

service:
    extensions: [zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp, otlphttp, zipkin]
        metrics:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, prometheus]
        logs:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, loki, elasticsearch]
    telemetry:
        metrics:
            address: "0.0.0.0:8888"
            level: "detailed"
        logs:
            level: "debug"

extensions:
    zpages:
        endpoint: "0.0.0.0:55679"