receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    batch:
    attributes:
        actions:
            - key: team
              action: insert
              value: huntercodexs

exporters:
    debug:

    ### 6. OTEL-FORWARD > OTEL-OPENSEARCH > LOKI
    loki:
        endpoint: http://loki:3100/loki/api/v1/push

    ### 7. OTEL-FORWARD > OTEL-OPENSEARCH > TEMPO
    otlp:
        endpoint: tempo:4317
        tls:
            insecure: true

    ### 8. OTEL-FORWARD > OTEL-OPENSEARCH > JAEGER
    otlphttp:
        endpoint: http://jaeger:4318
        tls:
            insecure: true

    ### 9. OTEL-FORWARD > OTEL-OPENSEARCH > OPENSEARCH
    opensearch:
        endpoint: "https://node-0.example.com:9200"
        logs_index: "otel-collector-opensearch-v1-2025.06.09"
        tls:
            insecure: false
            ca_file: "/etc/ssl/certs/opensearch.crt"
        headers:
            Authorization: "Basic ${OPENSEARCH_AUTHORIZATION}"

    ### 10. OTEL-FORWARD > OTEL-OPENSEARCH > DATA-PREPPER
    otlp/data_prepper:
        endpoint: data-prepper:21890
        tls:
            insecure: true #true|false
            #ca_file:
            #cert_file:
            #key_file:

service:
    extensions: [zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp, otlphttp, otlp/data_prepper]
        metrics:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, otlp/data_prepper]
        logs:
            receivers: [otlp]
            processors: [attributes, batch]
            exporters: [debug, loki, opensearch, otlp/data_prepper]
    telemetry:
        metrics:
            address: "0.0.0.0:8888"
            level: "detailed"
        logs:
            level: "debug"

extensions:
    zpages:
        endpoint: "0.0.0.0:55679"