version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        ports:
            - ${OPENJDK_8U212_PORT}:38001
        volumes:
            - ./app/:/home/openjdk8u212/
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk8u212/JAVA-MSSQL-22.01.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u212/application.properties"
    #----------------------------------------------------------------------------------------
    mssql:
        env_file: .env
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - ${MSSQL_PORT}:1433
        volumes:
            - type: bind
              source: ./mssql/lib
              target: /var/lib/mssql/data/
              read_only: false
            - type: bind
              source: ./mssql/opt
              target: /var/opt/mssql/data/
              read_only: false
        environment:
            SA_PASSWORD: ${MSSQL_SA_PASSWORD}
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
            ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
            MSSQL_PID: ${MSSQL_EDITION}
            TRUSTED_CONNECTION: ${MSSQL_TRUSTED_CONNECTION}
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    mssql-tools:
        env_file: .env
        container_name: mssql-tools
        image:  mcr.microsoft.com/mssql-tools
        ports:
            - ${MSSQL_TOOLS_PORT}:10000
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true