version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u232:
        env_file: .env
        container_name: openjdk-8u232
        build:
            context: .
            dockerfile: openjdk-8u232.dockerfile
        ports:
            - ${OPENJDK_8U232_PORT1}:38801
        volumes:
            - ./microservices/users/:/home/openjdk8u232/microservices/users/
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk8u232/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u232/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true