version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    nginx:
        env_file: .env
        container_name: nginx
        image: nginx:latest
        privileged: true
        ports:
            - ${NGINX_PHP740_PORT}:80
            - ${NGINX_PHP800_PORT}:81
            - ${NGINX_PHP810_PORT}:82
            - ${NGINX_PHP822_PORT}:83
            - ${NGINX_PHP8213_PORT}:84
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/404.html:/usr/share/nginx/html/404.html
            - ./nginx/500.html:/usr/share/nginx/html/500.html
            - ./applications/:/var/www/webserver/applications/
        working_dir: /etc/nginx
        links:
            - php-7.4.0
            - php-8.0.0
            - php-8.1.0
            - php-8.2.2
            - php-8.2.13
        depends_on:
            - php-7.4.0
            - php-8.0.0
            - php-8.1.0
            - php-8.2.2
            - php-8.2.13
        networks:
            - default
            - nginx_php8_mysql-offline-drivers_network
    #----------------------------------------------------------------------------------------
    php-7.4.0:
        env_file: .env
        container_name: php-7.4.0
        build:
            context: ./php/7.4.0
            dockerfile: php-7.4.0.dockerfile
        ports:
            - ${PHP740_PORT}:9000
        volumes:
            - ./php/7.4.0/conf/:/home/php/conf/
            - ./php/7.4.0/shared/:/home/php/shared/
            - ./applications/php-7.4.0/:/var/www/webserver/applications/php-7.4.0/
        networks:
            - nginx_php8_mysql-offline-drivers_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.0.0:
        env_file: .env
        container_name: php-8.0.0
        build:
            context: ./php/8.0.0
            dockerfile: php-8.0.0.dockerfile
        ports:
            - ${PHP800_PORT}:9000
        volumes:
            - ./php/8.0.0/conf/:/home/php/conf/
            - ./php/8.0.0/shared/:/home/php/shared/
            - ./applications/php-8.0.0/:/var/www/webserver/applications/php-8.0.0/
        networks:
            - nginx_php8_mysql-offline-drivers_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.1.0:
        env_file: .env
        container_name: php-8.1.0
        build:
            context: ./php/8.1.0
            dockerfile: php-8.1.0.dockerfile
        ports:
            - ${PHP810_PORT}:9000
        volumes:
            - ./php/8.1.0/conf/:/home/php/conf/
            - ./php/8.1.0/shared/:/home/php/shared/
            - ./applications/php-8.1.0/:/var/www/webserver/applications/php-8.1.0/
        networks:
            - nginx_php8_mysql-offline-drivers_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.2.2:
        env_file: .env
        container_name: php-8.2.2
        build:
            context: ./php/8.2.2
            dockerfile: php-8.2.2.dockerfile
        ports:
            - ${PHP822_PORT}:9000
        volumes:
            - ./php/8.2.2/conf/:/home/php/conf/
            - ./php/8.2.2/shared/:/home/php/shared/
            - ./applications/php-8.2.2/:/var/www/webserver/applications/php-8.2.2/
        networks:
            - nginx_php8_mysql-offline-drivers_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    php-8.2.13:
        env_file: .env
        container_name: php-8.2.13
        build:
            context: ./php/8.2.13
            dockerfile: php-8.2.13.dockerfile
        ports:
            - ${PHP8213_PORT}:9000
        volumes:
            - ./php/8.2.13/conf/:/home/php/conf/
            - ./php/8.2.13/shared/:/home/php/shared/
            - ./applications/php-8.2.13/:/var/www/webserver/applications/php-8.2.13/
        networks:
            - nginx_php8_mysql-offline-drivers_network
        #command: "/home/php/conf/custom.sh"
    #----------------------------------------------------------------------------------------
    mysql-80:
        env_file: .env
        image: mysql:8.0
        container_name: mysql80
        ports:
            - ${MYSQL80_PORT}:3306
        volumes:
            - ./mysql-8.0/lib:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        tty: true
        networks:
            - default
            - nginx_php8_mysql-offline-drivers_network
    #----------------------------------------------------------------------------------------
    mysql-57:
        env_file: .env
        image: mysql:5.7
        container_name: mysql57
        ports:
            - ${MYSQL57_PORT}:3306
        volumes:
            - ./mysql-5.7/lib:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: ${MYSQL57_DATABASE}
            MYSQL_USERNAME: ${MYSQL57_USERNAME}
            MYSQL_PASSWORD: ${MYSQL57_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL57_ROOT_PASSWORD}
        tty: true
        networks:
            - default
            - nginx_php8_mysql-offline-drivers_network
    #----------------------------------------------------------------------------------------

networks:
    nginx_php8_mysql-offline-drivers_network:
        external: true
        