version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-17:
        env_file: .env
        container_name: openjdk-17
        build:
            context: .
            dockerfile: openjdk-17.dockerfile
        volumes:
            - ./microservices/users/:/home/openjdk17/microservices/users/
        ports:
            - ${OPENJDK_17_PORT1}:38801
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk17/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk17/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true