version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    swagger-editor:
        env_file: .env
        image: swaggerapi/swagger-editor
        container_name: swagger-editor
#        build:
#            context: ./
#            dockerfile: swagger-editor.dockerfile
        ports:
           - ${SWAGGER_EDITOR_PORT}:8080
        volumes:
           - ./share/:/home/swagger-editor/
        tty: true
        networks:
           - default
           - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
