version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    kibana:
        env_file: .env
        container_name: kibana
        image: kibana:${GENERAL_STACK_VERSION}
        ports:
            - ${KIBANA_PORT}:5601
        volumes:
            - type: bind
              source: ./config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        environment:
            ELASTIC_VERSION: ${GENERAL_STACK_VERSION}
            ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HTTP_HOSTS}
            ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
            KIBANA_PASSWORD: ${KIBANA_PASSWORD}
            KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
