FROM node:18.13.0

ARG ANGULAR_PROJECT_NAME

ENV ANGULAR_APP_NAME $ANGULAR_PROJECT_NAME

RUN mkdir -p /$ANGULAR_APP_NAME
WORKDIR /$ANGULAR_APP_NAME
RUN cd /$ANGULAR_APP_NAME

## ANGULAR CLI
RUN npm install -g @angular/cli

COPY ./app/* /$ANGULAR_APP_NAME/

EXPOSE 4200
EXPOSE 8080
