version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    jenkins:
        env_file: .env
        container_name: jenkins
        build:
            context: ./
            dockerfile: jenkins.dockerfile
        ports:
            - ${JENKINS_HTTP_PORT}:8080
            - ${JENKINS_AGENT_PORT}:50000
        volumes:
            - ./share/:/home/jenkins/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
