version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        ports:
            - ${OPENJDK_8U212_PORT}:38001
        volumes:
            - ./app/:/home/openjdk8u212/
        tty: true
        networks:
            - default
            - open_network
        depends_on:
            - mongo
        links:
            - mongo
        command: "java -jar /home/openjdk8u212/JAVA-MONGODB-22.01.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u212/application.properties"
    #----------------------------------------------------------------------------------------
    mongo:
        env_file: .env
        container_name: mongo
        image: mongo
        ports:
            - ${MONGO_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_DB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_DB_ROOT_PASSWORD}
        volumes:
            -   type: bind
                source: ./mongodb/mongo/MongoDB
                target: /data/db/
                read_only: false
            -   type: bind
                source: ./mongodb/mongo/mongod.conf
                target: /etc/mongod.conf
                read_only: false
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    mongo-express:
        env_file: .env
        container_name: mongo-express
        image: mongo-express
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: ${MONGO_EXPRESS_SERVER_DRIVER}
            ME_CONFIG_MONGODB_PORT: ${MONGO_EXPRESS_SERVER_PORT}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_SERVER_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_SERVER_PASSWORD}
            ME_CONFIG_MONGODB_URL: ${MONGO_EXPRESS_SERVER_URL}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
        tty: true
        links:
            - mongo
        depends_on:
            - mongo
        networks:
            - default
            - open_network
    #-----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true