version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    mysql-80:
        env_file: .env
        image: mysql:8.0
        container_name: mysql-80
        ports:
            - ${MYSQL80_PORT}:3306
        volumes:
            - ./lib:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true