version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    webserver:
        env_file: .env
        image: httpd:2.4.54
        container_name: webserver
        ports:
            - ${WEBSERVER_PORT1}:80
            - ${WEBSERVER_PORT2}:443
        privileged: true
        volumes:
            - ./webserver/:/home/webserver/
            - ./applications/:/var/www/webserver/
        tty: true
        depends_on:
            - php8
        links:
            - php8
        networks:
            - webserver_network
    #----------------------------------------------------------------------------------------
    php8:
        env_file: .env
        container_name: php8
        build:
            context: ./php8
            dockerfile: php8.dockerfile
        ports:
            - ${PHP8_PORT}:9000
        volumes:
            - ./applications/:/var/www/webserver/
        networks:
            - webserver_network
    #----------------------------------------------------------------------------------------

networks:
    webserver_network:
        external: true
