version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    proxy:
        env_file: .env
        image: httpd:2.4.54
        container_name: proxy
        ports:
            - ${PROXY_HTTP_PORT}:80
            - ${PROXY_HTTPS_PORT}:443
        privileged: true
        volumes:
            - ./proxy/:/home/proxy/
            - ./proxy/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./proxy/conf/proxy.conf:/usr/local/apache2/conf/proxy.conf
        tty: true
        networks:
            default:
            open_network:
            reverse_proxy:
                ipv4_address: 10.0.0.2
    #----------------------------------------------------------------------------------------
    webserver:
        env_file: .env
        image: httpd:2.4.54
        container_name: webserver
        privileged: true
        volumes:
            - ./webserver/:/home/webserver/
            - ./webserver/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./webserver/conf/webserver.conf:/usr/local/apache2/conf/webserver.conf
            - ./applications/:/var/www/webserver/
        tty: true
        depends_on:
            - php8
        links:
            - php8
        networks:
            reverse_proxy:
                ipv4_address: 10.0.0.3
    #----------------------------------------------------------------------------------------
    php8:
        env_file: .env
        container_name: php8
        build:
            context: ./php8
            dockerfile: php8.dockerfile
        volumes:
            - ./applications/:/var/www/webserver/
        networks:
            reverse_proxy:
                ipv4_address: 10.0.0.4
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
    reverse_proxy:
        external: false
        internal: true
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
