version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    fedora-rpm:
        env_file: .env
        container_name: fedora-rpm
        #image: fedora
        build:
            context: .
            dockerfile: fedora-rpm.dockerfile
        ports:
            - ${FEDORA_RPM_PORT}:35900
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
