version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    rockylinux-rpm:
        env_file: .env
        container_name: rockylinux-rpm
        #image: rockylinux
        build:
            context: .
            dockerfile: rockylinux-rpm.dockerfile
        ports:
            - ${ROCKY_LINUX_RPM_PORT}:35900
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
