version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    swagger-ui:
        env_file: .env
        image: swaggerapi/swagger-ui
        container_name: swagger-ui
#        build:
#            context: ./
#            dockerfile: swagger-ui.dockerfile
        ports:
            - ${SWAGGER_UI_PORT}:8080
        volumes:
            - ./share/:/home/swagger-ui/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
