version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    nodejs-react:
        env_file: .env
        build:
            context: ./
            dockerfile: nodejs-react.dockerfile
            args:
                REACT_PROJECT_NAME: ${REACT_PROJECT_NAME}
        container_name: nodejs-react
        ports:
            - ${NODEJS_PORT1}:3000
            - ${NODEJS_PORT2}:8080
        volumes:
            - ./app/:/${REACT_PROJECT_NAME}
            - ./shared/:/home/nodejs-react/shared/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
        