version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    # NOTE: The sqlite don't can used remotely, so it is used inside php8 container
    sqlite3:
        env_file: .env
        container_name: sqlite3
        build:
            context: ./
            dockerfile: sqlite3.dockerfile
        privileged: true
        ports:
            - ${SQLITE3_PORT}:5050
        volumes:
            - type: bind
              source: ./sqliteDB/sqlite-autoconf
              target: /opt/sqlite3
              read_only: false
            - type: bind
              source: ./sqliteDB/databases
              target: /root/db/
              read_only: false
        stdin_open: true
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    
networks:
    open_network:
        external: true
