version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    otel-collector:
        env_file: .env
        image: otel/opentelemetry-collector-contrib
        volumes:
            - ./conf/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
        ports:
            - ${OPEN_TELEMETRY_PPROF_PORT}:1888
            - ${OPEN_TELEMETRY_PROMETHEUS_METRICS_PORT}:8888
            - ${OPEN_TELEMETRY_PROMETHEUS_EXPORTER_PORT}:8889
            - ${OPEN_TELEMETRY_HEALTH_CHECK_PORT}:13133
            - ${OPEN_TELEMETRY_OTLP_GRPC_PORT}:4317
            - ${OPEN_TELEMETRY_OTLP_HTTP_PORT}:4318
            - ${OPEN_TELEMETRY_ZPAGES_PORT}:55679
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
