version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    centos-rpm:
        env_file: .env
        container_name: centos-rpm
        #image: centos
        build:
            context: .
            dockerfile: centos-rpm.dockerfile
        ports:
            - ${CENTOS_RPM_PORT}:35900
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
