version: '3.8'
services:

    #----------------------------------------------------------------------------------------
    ## OPENTELEMETRY
    #----------------------------------------------------------------------------------------
    opentelemetry-collector:
        env_file: .env
        image: otel/opentelemetry-collector-contrib:latest
        container_name: opentelemetry-collector
        privileged: true
        tty: true
        volumes:
            - ./opentelemetry/conf/opentelemetry-config.yaml:/etc/opentelemetry-config.yaml
            - ./opentelemetry/shared/:/home/opentelemetry/shared/
        command: ["--config=/etc/opentelemetry-config.yaml"]
        ports:
            - ${OPEN_TELEMETRY_PPROF_PORT}:1888
            - ${OPEN_TELEMETRY_PROMETHEUS_METRICS_PORT}:8888
            - ${OPEN_TELEMETRY_PROMETHEUS_EXPORTER_PORT}:8889
            - ${OPEN_TELEMETRY_HEALTH_CHECK_PORT}:13133
            - ${OPEN_TELEMETRY_OTLP_GRPC_PORT}:4317
            - ${OPEN_TELEMETRY_OTLP_HTTP_PORT}:4318
            - ${OPEN_TELEMETRY_ZPAGES_PORT}:55679
        depends_on:
            - tempo
            - loki
            - jaeger
            - prometheus
            - grafana
            - opensearch-node-2-15
            - elasticsearch
            - logstash
            - kibana
            - zipkin
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## JAEGER-v1 (deprecated)
    #----------------------------------------------------------------------------------------
    jaeger:
        env_file: .env
        image: jaegertracing/all-in-one
        container_name: jaeger
        privileged: true
        tty: true
        volumes:
            - ./jaeger/shared/:/home/jaeger/shared/
        environment:
            COLLECTOR_OTLP_ENABLED: "true"
        ports:
            - ${JAEGER_PORT_GRPC}:14250
            - ${JAEGER_PORT_HTTP}:16686
            - ${JAEGER_PORT_OTLP}:16685
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## PROMETHEUS
    #----------------------------------------------------------------------------------------
    prometheus:
        env_file: .env
        image: prom/prometheus
        container_name: prometheus
        privileged: true
        tty: true
        command: [--config.file=/etc/prometheus/prometheus.yml]
        volumes:
            - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/shared/:/home/prometheus/shared/
        ports:
            - ${PROMETHEUS_PORT}:9090
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## GRAFANA
    #----------------------------------------------------------------------------------------
    grafana:
        env_file: .env
        image: grafana/grafana
        container_name: grafana
        privileged: true
        tty: true
        volumes:
            - ./grafana/conf/grafana.yml:/etc/grafana/provisioning/datasources/default.yml
            - ./grafana/shared/:/home/grafana/shared/
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - ${GRAFANA_PORT}:3000
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## LOKI
    #----------------------------------------------------------------------------------------
    loki:
        env_file: .env
        image: grafana/loki:3.2.0
        container_name: loki
        privileged: true
        tty: true
        volumes:
            - ./loki/conf/loki.yaml:/etc/loki/local-config.yaml
            - ./loki/shared/:/home/loki/shared/
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - ${LOKI_PORT}
            - ${LOKI_PORT_HOST}:${LOKI_PORT}
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## TEMPO
    #----------------------------------------------------------------------------------------
    tempo:
        env_file: .env
        image: grafana/tempo:latest
        container_name: tempo
        privileged: true
        tty: true
        volumes:
            - ./tempo/conf/tempo.yaml:/etc/tempo.yaml
            - ./tempo/shared/:/home/tempo/shared/
        command: [ "-config.file=/etc/tempo.yaml" ]
        ports:
            - ${TEMPO_OTLP_PORT}
            - ${TEMPO_HTTP_PORT}
            - ${TEMPO_OTLP_PORT_HOST}:${TEMPO_OTLP_PORT}
            - ${TEMPO_HTTP_PORT_HOST}:${TEMPO_HTTP_PORT}
            - ${TEMPO_HTTP_LISTEN_PORT_HOST}:${TEMPO_HTTP_LISTEN_PORT}
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## OPENSEARCH
    #----------------------------------------------------------------------------------------
    opensearch-node-2-15:
        env_file: .env
        image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
        container_name: opensearch-node-2-15
        privileged: true
        tty: true
        volumes:
            - opensearch-data:/usr/share/opensearch/data #see in volumes below
            - ./opensearch/conf:/usr/share/opensearch/config/opensearch-performance-analyzer
            - ./opensearch/shared/:/home/opensearch/shared/
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node-2-15
            - discovery.seed_hosts=opensearch-node-2-15
            - cluster.initial_cluster_manager_nodes=opensearch-node-2-15
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - ${OPENSEARCH_PORT_REST_API}:9200
            - ${OPENSEARCH_PORT_REST_ANALYZER}:9600
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## OPENSEARCH-DASHBOARDS
    #----------------------------------------------------------------------------------------
    opensearch-dashboards-2-15:
        env_file: .env
        image: opensearchproject/opensearch-dashboards:${OPENSEARCH_VERSION}
        container_name: opensearch-dashboards-2-15
        privileged: true
        tty: true
        volumes:
            - ./opensearch/shared/:/home/opensearch/shared/
        environment:
            OPENSEARCH_HOSTS: '["https://opensearch-node-2-15:9200"]'
        ports:
            - ${OPENSEARCH_PORT_WEB}:5601
        expose:
            - ${OPENSEARCH_PORT_WEB}
        depends_on:
            - opensearch-node-2-15
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## ELASTICSEARCH
    #----------------------------------------------------------------------------------------
    elasticsearch:
        env_file: .env
        image: elasticsearch:${GENERAL_STACK_VERSION}
        container_name: elasticsearch
        privileged: true
        tty: true
        volumes:
            - ./elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/shared/:/home/elasticsearch/shared/
        environment:
            ELASTIC_VERSION: ${GENERAL_STACK_VERSION}
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
            KIBANA_USERNAME: ${KIBANA_SYSTEM_USERNAME}
            KIBANA_SYSTEM_USERNAME: ${KIBANA_SYSTEM_USERNAME}
            LOGSTASH_INTERNAL_USERNAME: ${LOGSTASH_INTERNAL_USERNAME}
            LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
            ES_JAVA_OPTS: ${ELASTICSEARCH_JAVA_OPTS}
        ports:
            - ${ELASTICSEARCH_PORT_1}:9200
            - ${ELASTICSEARCH_PORT_2}:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## LOGSTASH
    #----------------------------------------------------------------------------------------
    logstash:
        env_file: .env
        image: logstash:${GENERAL_STACK_VERSION}
        container_name: logstash
        privileged: true
        tty: true
        volumes:
            - ./logstash/pipeline:/usr/share/logstash/pipeline
            - ./logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
            - ./logstash/script/logstash-reload.sh:/home/logstash/logstash-reload.sh
            - ./logstash/shared/:/home/logstash/shared/
        environment:
            ELASTIC_VERSION: ${GENERAL_STACK_VERSION}
            LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
            LS_JAVA_OPTS: ${LOGSTASH_JAVA_OPTS}
        ports:
            - ${LOGSTASH_PORT_HTTP}:8080
            - ${LOGSTASH_PORT_1}:5044
            - ${LOGSTASH_PORT_2}:9600
            - ${LOGSTASH_TCP_PORT}:5000/tcp
            - ${LOGSTASH_UDP_PORT}:5000/udp
        depends_on:
            - elasticsearch
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## KIBANA
    #----------------------------------------------------------------------------------------
    kibana:
        env_file: .env
        image: kibana:${GENERAL_STACK_VERSION}
        container_name: kibana
        privileged: true
        tty: true
        volumes:
            - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
            - ./kibana/shared/:/home/kibana/shared/
        environment:
            ELASTIC_VERSION: ${GENERAL_STACK_VERSION}
            ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HTTP_HOSTS}
            ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
            KIBANA_PASSWORD: ${KIBANA_PASSWORD}
            KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
        ports:
            - ${KIBANA_PORT_HOST}:5601
        depends_on:
            - elasticsearch
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------
    ## ZIPKIN
    #----------------------------------------------------------------------------------------
    zipkin:
        env_file: .env
        image: openzipkin/zipkin
        container_name: zipkin
        privileged: true
        tty: true
        volumes:
            - ./zipkin/conf/basic-auth.properties:/home/zipkin/properties/basic-auth.properties
            - ./zipkin/shared/:/home/zipkin/shared/
        environment:
            STORAGE_TYPE: ${ZIPKIN_STORAGE_TYPE}
            SEARCH_ENABLED: ${ZIPKIN_SEARCH_ENABLED}
            #ES_HTTP_LOGGING: ${ZIPKIN_HTTP_LOGGING}
            ES_USERNAME: ${ELASTIC_USERNAME}
            ES_PASSWORD: ${ELASTIC_PASSWORD}
            ES_HOSTS: ${ELASTICSEARCH_HTTP_HOSTS}
            ES_SSL_NO_VERIFY: ${SECURITY_ZIPKIN_NO_SSL_CHECK}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9411/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
        ports:
            - ${ZIPKIN_PORT}:9411
        depends_on:
            - elasticsearch
        networks:
            - default
            - observability_network_v1
    #----------------------------------------------------------------------------------------

volumes:
    opensearch-data:
    elasticsearch:

networks:
    observability_network_v1:
