version: '3.7'
services:

  #----------------------------------------------------------------------------------------
  elasticsearch:
    env_file: .env
    container_name: elasticsearch
    image: elasticsearch:${STACK_VERSION}
    ports:
      - ${ES_PORT_1}:9200
      - ${ES_PORT_2}:9300
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: elasticsearch
        target: /usr/share/elasticsearch/data
        read_only: false
    environment:
      ELASTIC_VERSION: ${STACK_VERSION}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_USERNAME: ${KIBANA_SYSTEM_USERNAME}
      KIBANA_SYSTEM_USERNAME: ${KIBANA_SYSTEM_USERNAME}
      LOGSTASH_INTERNAL_USERNAME: ${LOGSTASH_INTERNAL_USERNAME}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
  #----------------------------------------------------------------------------------------
  kibana:
    env_file: .env
    container_name: kibana
    image: kibana:${STACK_VERSION}
    ports:
      - ${KB_PORT}:5601
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      ELASTIC_VERSION: ${STACK_VERSION}
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    depends_on:
      - elasticsearch
  #----------------------------------------------------------------------------------------
  logstash:
    env_file: .env
    container_name: logstash
    image: logstash:${STACK_VERSION}
    ports:
      - ${LS_PORT_HTTP}:8080
      - ${LS_PORT_1}:5044
      - ${LS_PORT_2}:9600
      - ${LS_TCP_PORT}:5000/tcp
      - ${LS_UDP_PORT}:5000/udp
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
    environment:
      ELASTIC_VERSION: ${STACK_VERSION}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
      LS_JAVA_OPTS: ${LS_JAVA_OPTS}
    depends_on:
      - elasticsearch
  #----------------------------------------------------------------------------------------
  grafana:
    env_file: .env
    container_name: grafana
    image: grafana/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - type: bind
        source: ./grafana
        target: /home/grafana/
        read_only: true
    tty: true
  #----------------------------------------------------------------------------------------
  grafana-ubuntu:
    env_file: .env
    container_name: grafana-ubuntu
    image: grafana/grafana-enterprise:8.4.6-ubuntu
    ports:
      - ${GRAFANA_UBUNTU_PORT}:3000
    volumes:
      - type: bind
        source: ./grafana-ubuntu
        target: /home/grafana/
        read_only: true
    tty: true
  #----------------------------------------------------------------------------------------
  prometheus:
    env_file: .env
    container_name: prometheus
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
    tty: true
  #----------------------------------------------------------------------------------------

volumes:
  elastcsearch:
