version: "3.7"
services:
    
    #------------------------------------------------------------
    nginx:
        env_file: .env
        container_name: nginx
        image: nginx:latest
        privileged: true
        ports:
            - ${NGINX_PORT}:85
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/proxy.conf:/etc/nginx/proxy.conf
            - ./etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./etc/nginx/mime.types:/etc/nginx/mime.types
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
            - ./etc/nginx/logs/:/var/log/nginx/
            - ./htdocs/:/var/www/htdocs/
        working_dir: /etc/nginx
        tty: true
        networks:
            default:
            open_network:
            reverse_proxy:
                ipv4_address: 10.0.0.2
    #------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        privileged: true
        tty: true
        networks:
            reverse_proxy:
                ipv4_address: 10.0.0.3
    #------------------------------------------------------------
    
networks:
    open_network:
        external: true
    reverse_proxy:
        external: false
        internal: true
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
        