version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        ports:
            - ${OPENJDK_8U212_PORT1}:38801
            - ${OPENJDK_8U212_PORT2}:38802
            - ${OPENJDK_8U212_PORT3}:38803
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true