version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        volumes:
            - ./microservices/users/:/home/openjdk8u212/microservices/users/
        ports:
            - ${OPENJDK_8U212_PORT1}:38801
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk8u212/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u212/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true