version: "3.7"
services:
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        image: openjdk:8u212
        container_name: openjdk-8u212
        #build: ./java/openjdk-8u212/dockerfile/
        ports:
            - "31899:8080"
        #volumes:
        #  - "./java/openjdk-8u212/:/etc/openjdk-8u212/"
        #    links:
        #      - mysql-80
        tty: true
    #----------------------------------------------------------------------------------------
    mysql-80:
        image: mysql:8.0
        container_name: mysql80
        ports:
            - "3706:3306"
        volumes:
            - "./mysql-80:/var/lib/mysql/"
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
    #----------------------------------------------------------------------------------------

networks:
    self_containers_gateway:
        driver: bridge
