version: "3.7"
services:
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        image: openjdk:8u212
        container_name: openjdk-8u212
        ports:
            - "31890:31890"
        volumes:
            - type: bind
              source: ./java/simple-api-demo
              target: /home/openjdk/simple-api-demo
              read_only: false
        tty: true
        networks:
            - openjdk-net
        command: "java -jar /home/openjdk/simple-api-demo/SIMPLE-API-DEMO-22.01.1-SNAPSHOT.jar"
    #----------------------------------------------------------------------------------------
    mysql-80-to-jdk:
        env_file: .env
        image: mysql:8.0
        container_name: mysql-80-to-jdk
        ports:
            - "3706:3306"
        volumes:
            - type: bind
              source: ./mysql-80
              target: /var/lib/mysql/
              read_only: false
        environment:
            MYSQL_DATABASE: ${MYSQL80_DATABASE}
            MYSQL_USERNAME: ${MYSQL80_USERNAME}
            MYSQL_PASSWORD: ${MYSQL80_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL80_ROOT_PASSWORD}
        tty: true
        networks:
            - openjdk-net
    #----------------------------------------------------------------------------------------

networks:
    openjdk-net:
        driver: bridge
