version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    python-3.12.1:
        env_file: .env
        container_name: python-3.12.1
        build:
            context: ./
            dockerfile: python-3.12.1.dockerfile
        ports:
            - ${PYTHON3_PORT1}:55001
            - ${PYTHON3_PORT2}:55002
            - ${PYTHON3_PORT3}:31800
        volumes:
            - ./shared/:/home/python-3.12.1/shared/
            - ./applications/:/home/python-3.12.1/applications/
        tty: true
        command: "bash /home/python-3.12.1/applications/applications-deploy.sh"
        networks:
            open_network:
    #----------------------------------------------------------------------------------------
    
networks:
    open_network:
        external: true

