version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    mysql-5.7:
        env_file: .env
        image: mysql:5.7
        container_name: mysql-5.7
        ports:
            - ${MYSQL57_PORT}:3306
        volumes:
            - ./lib:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: ${MYSQL57_DATABASE}
            MYSQL_USERNAME: ${MYSQL57_USERNAME}
            MYSQL_PASSWORD: ${MYSQL57_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL57_ROOT_PASSWORD}
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true