version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    caserver:
        env_file: .env
        container_name: caserver
        restart: always
        privileged: true
        build:
            context: ./
            dockerfile: ca-server-ubuntu2004.dockerfile
        ports:
            - ${CA_SERVER_PORT}:35900
        volumes:
            - ./share/:/home/causer/share/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    nginx-ssl:
        env_file: .env
        container_name: nginx-ssl
        build:
            context: ./
            dockerfile: nginx-ssl.dockerfile
        ports:
            - ${NGINX_SSL_HTTP_PORT}:80
            - ${NGINX_SSL_HTTPS_PORT}:443
        volumes:
            - ./share/:/home/ubuntu/
            - ./nginx/:/etc/nginx/
        tty: true
        networks:
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
