version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    caserver:
        env_file: .env
        container_name: caserver
        restart: always
        privileged: true
        build:
            context: ./
            dockerfile: ca-server-ubuntu2004.dockerfile
        ports:
            - ${CA_SERVER_PORT}:35900
        volumes:
            - ./share/:/home/causer/
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
