version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    caserver:
        env_file: .env
        container_name: caserver
        restart: always
        privileged: true
        build:
            context: ./
            dockerfile: ca-server-ubuntu2004.dockerfile
            args:
                CA_SERVER_COUNTRY: ${CA_SERVER_COUNTRY}
                CA_SERVER_PROVINCE: ${CA_SERVER_PROVINCE}
                CA_SERVER_CITY: ${CA_SERVER_CITY}
                CA_SERVER_ORG: ${CA_SERVER_ORG}
                CA_SERVER_EMAIL: ${CA_SERVER_EMAIL}
                CA_SERVER_ORGANIZATION_UNIT_NAME: ${CA_SERVER_ORGANIZATION_UNIT_NAME}
                CA_SERVER_ALGORITHM: ${CA_SERVER_ALGORITHM}
                CA_SERVER_DIGEST: ${CA_SERVER_DIGEST}
        ports:
            - ${CA_SERVER_PORT}:35900
        volumes:
            - ./share/:/home/causer/share/
        tty: true
        networks:
            restrict_network:
                ipv4_address: 10.0.0.2
    #----------------------------------------------------------------------------------------
    nginx-ssl-server1:
        env_file: .env
        container_name: nginx-ssl-server1
        privileged: true
        build:
            context: ./
            dockerfile: nginx-ssl-server1.dockerfile
            args:
                NGINX_SSL_1_COUNTRY: ${NGINX_SSL_1_COUNTRY}
                NGINX_SSL_1_STATE: ${NGINX_SSL_1_STATE}
                NGINX_SSL_1_CITY: ${NGINX_SSL_1_CITY}
                NGINX_SSL_1_ORGANIZATION: ${NGINX_SSL_1_ORGANIZATION}
                NGINX_SSL_1_ORGANIZATION_UNIT_NAME: ${NGINX_SSL_1_ORGANIZATION_UNIT_NAME}
                NGINX_SSL_1_COMMON_NAME: ${NGINX_SSL_1_COMMON_NAME}
                NGINX_SSL_1_EMAIL_ADDRESS: ${NGINX_SSL_1_EMAIL_ADDRESS}
        ports:
            - ${NGINX_SSL_1_HTTP_PORT}:80
            - ${NGINX_SSL_1_HTTPS_PORT}:443
        volumes:
            - ./share/:/home/ubuntu/
            - ./app1/:/var/www/app
            - ./nginx-ssl-server-1/:/etc/nginx/
        tty: true
        networks:
            open_network:
            restrict_network:
                ipv4_address: 10.0.0.3
        depends_on:
            - caserver
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
    restrict_network:
        external: false
        internal: true
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
