version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u212:
        env_file: .env
        container_name: openjdk-8u212
        build:
            context: .
            dockerfile: openjdk-8u212.dockerfile
        ports:
            - ${OPENJDK_8U212_PORT}:38001
        volumes:
            - ./app/:/home/openjdk8u212/
        tty: true
        networks:
            - default
            - open_network
        command: "java -jar /home/openjdk8u212/JAVA-FIREBIRD-22.01.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u212/application.properties"
    #----------------------------------------------------------------------------------------
    firebird:
        env_file: .env
        container_name: firebird
        privileged: true
        build:
            context: ./firebird
            dockerfile: firebird.dockerfile
            args:
                TZ: ${FIREBIRD_TIMEZONE}
                ISC_PASSWORD: ${FIREBIRD_ISC_PASSWORD}
                FIREBIRD_USER: ${FIREBIRD_USER}
                FIREBIRD_DBNAME: ${FIREBIRD_DBNAME}
        ports:
            - ${FIREBIRD_PORT}:3050
        volumes:
            - ./firebird/data/:/etc/firebird/3.0/
        environment:
            TZ: ${FIREBIRD_TIMEZONE}
            FIREBIRD_DATABASE: ${FIREBIRD_DBNAME}
            FIREBIRD_USER: ${FIREBIRD_USER}
            FIREBIRD_PASS: ${FIREBIRD_ISC_PASSWORD}
            ISC_PASSWORD: ${FIREBIRD_ISC_PASSWORD}
        tty: true
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true