version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    amazonlinux-rpm:
        env_file: .env
        container_name: amazonlinux-rpm
        #image: amazonlinux
        build:
            context: .
            dockerfile: amazonlinux-rpm.dockerfile
        ports:
            - ${AMAZONLINUX_RPM_PORT}:35900
        privileged: true
        tty: true
        volumes:
            - ./shared/:/home/shared/
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true
