version: '3.8'
services:

    #----------------------------------------------------------------------------------------
    opensearch-node-latest:
        env_file: .env
        image: opensearchproject/opensearch:latest
        container_name: opensearch-node-latest
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node-latest
            - discovery.seed_hosts=opensearch-node-latest
            - cluster.initial_cluster_manager_nodes=opensearch-node-latest
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - opensearch-data:/usr/share/opensearch/data
            - ./conf:/usr/share/opensearch/config/opensearch-performance-analyzer
        ports:
            - ${OPENSEARCH_PORT_REST_API}:9200
            - ${OPENSEARCH_PORT_REST_ANALYZER}:9600
        networks:
            - opensearch-net
    #----------------------------------------------------------------------------------------
    opensearch-dashboards-latest:
        image: opensearchproject/opensearch-dashboards:latest
        container_name: opensearch-dashboards-latest
        ports:
            - ${OPENSEARCH_PORT_WEB}:5601
        expose:
            - ${OPENSEARCH_PORT_WEB}
        environment:
            OPENSEARCH_HOSTS: '["https://opensearch-node-latest:9200"]'
        networks:
            - opensearch-net
        depends_on:
            - opensearch-node-latest
    #----------------------------------------------------------------------------------------

volumes:
    opensearch-data:

networks:
    opensearch-net:

