version: "3.7"
services:
    
    #----------------------------------------------------------------------------------------
    openjdk-8u231:
        env_file: .env
        container_name: openjdk-8u231
        build:
            context: .
            dockerfile: openjdk-8u231.dockerfile
        ports:
            - ${OPENJDK_8U231_PORT1}:38801
        volumes:
            - ./microservices/users/:/home/openjdk8u231/microservices/users/
        tty: true
        networks:
            - default
            - open_network
        command: "/usr/bin/java -jar /home/openjdk8u231/microservices/users/SIMPLE-API-USERS-0.0.1-SNAPSHOT.jar --spring.config.location=/home/openjdk8u231/microservices/users/application.properties"
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true